#ifndef ERRNOTAB_H
#define ERRNOTAB_H

t_errno errno_tab[] = {
        [  1] = {.name = "EPERM", .desc = ""},
        [  2] = {.name = "ENOENT", .desc = ""},
        [  3] = {.name = "ESRCH", .desc = ""},
        [  4] = {.name = "EINTR", .desc = ""},
        [  5] = {.name = "EIO", .desc = ""},
        [  6] = {.name = "ENXIO", .desc = ""},
        [  7] = {.name = "E2BIG", .desc = ""},
        [  8] = {.name = "ENOEXEC", .desc = ""},
        [  9] = {.name = "EBADF", .desc = ""},
        [ 10] = {.name = "ECHILD", .desc = ""},
        [ 11] = {.name = "EAGAIN", .desc = ""},
        [ 12] = {.name = "ENOMEM", .desc = ""},
        [ 13] = {.name = "EACCES", .desc = ""},
        [ 14] = {.name = "EFAULT", .desc = ""},
        [ 15] = {.name = "ENOTBLK", .desc = ""},
        [ 16] = {.name = "EBUSY", .desc = ""},
        [ 17] = {.name = "EEXIST", .desc = ""},
        [ 18] = {.name = "EXDEV", .desc = ""},
        [ 19] = {.name = "ENODEV", .desc = ""},
        [ 20] = {.name = "ENOTDIR", .desc = ""},
        [ 21] = {.name = "EISDIR", .desc = ""},
        [ 22] = {.name = "EINVAL", .desc = ""},
        [ 23] = {.name = "ENFILE", .desc = ""},
        [ 24] = {.name = "EMFILE", .desc = ""},
        [ 25] = {.name = "ENOTTY", .desc = ""},
        [ 26] = {.name = "ETXTBSY", .desc = ""},
        [ 27] = {.name = "EFBIG", .desc = ""},
        [ 28] = {.name = "ENOSPC", .desc = ""},
        [ 29] = {.name = "ESPIPE", .desc = ""},
        [ 30] = {.name = "EROFS", .desc = ""},
        [ 31] = {.name = "EMLINK", .desc = ""},
        [ 32] = {.name = "EPIPE", .desc = ""},
        [ 33] = {.name = "EDOM", .desc = ""},
        [ 34] = {.name = "ERANGE", .desc = ""},
        [ 35] = {.name = "EDEADLK", .desc = ""},
        [ 36] = {.name = "ENAMETOOLONG", .desc = ""},
        [ 37] = {.name = "ENOLCK", .desc = ""},
        [ 38] = {.name = "ENOSYS", .desc = ""},
        [ 39] = {.name = "ENOTEMPTY", .desc = ""},
        [ 40] = {.name = "ELOOP", .desc = ""},
        [ 42] = {.name = "ENOMSG", .desc = ""},
        [ 43] = {.name = "EIDRM", .desc = ""},
        [ 44] = {.name = "ECHRNG", .desc = ""},
        [ 45] = {.name = "EL2NSYNC", .desc = ""},
        [ 46] = {.name = "EL3HLT", .desc = ""},
        [ 47] = {.name = "EL3RST", .desc = ""},
        [ 48] = {.name = "ELNRNG", .desc = ""},
        [ 49] = {.name = "EUNATCH", .desc = ""},
        [ 50] = {.name = "ENOCSI", .desc = ""},
        [ 51] = {.name = "EL2HLT", .desc = ""},
        [ 52] = {.name = "EBADE", .desc = ""},
        [ 53] = {.name = "EBADR", .desc = ""},
        [ 54] = {.name = "EXFULL", .desc = ""},
        [ 55] = {.name = "ENOANO", .desc = ""},
        [ 56] = {.name = "EBADRQC", .desc = ""},
        [ 57] = {.name = "EBADSLT", .desc = ""},
        [ 59] = {.name = "EBFONT", .desc = ""},
        [ 60] = {.name = "ENOSTR", .desc = ""},
        [ 61] = {.name = "ENODATA", .desc = ""},
        [ 62] = {.name = "ETIME", .desc = ""},
        [ 63] = {.name = "ENOSR", .desc = ""},
        [ 64] = {.name = "ENONET", .desc = ""},
        [ 65] = {.name = "ENOPKG", .desc = ""},
        [ 66] = {.name = "EREMOTE", .desc = ""},
        [ 67] = {.name = "ENOLINK", .desc = ""},
        [ 68] = {.name = "EADV", .desc = ""},
        [ 69] = {.name = "ESRMNT", .desc = ""},
        [ 70] = {.name = "ECOMM", .desc = ""},
        [ 71] = {.name = "EPROTO", .desc = ""},
        [ 72] = {.name = "EMULTIHOP", .desc = ""},
        [ 73] = {.name = "EDOTDOT", .desc = ""},
        [ 74] = {.name = "EBADMSG", .desc = ""},
        [ 75] = {.name = "EOVERFLOW", .desc = ""},
        [ 76] = {.name = "ENOTUNIQ", .desc = ""},
        [ 77] = {.name = "EBADFD", .desc = ""},
        [ 78] = {.name = "EREMCHG", .desc = ""},
        [ 79] = {.name = "ELIBACC", .desc = ""},
        [ 80] = {.name = "ELIBBAD", .desc = ""},
        [ 81] = {.name = "ELIBSCN", .desc = ""},
        [ 82] = {.name = "ELIBMAX", .desc = ""},
        [ 83] = {.name = "ELIBEXEC", .desc = ""},
        [ 84] = {.name = "EILSEQ", .desc = ""},
        [ 85] = {.name = "ERESTART", .desc = ""},
        [ 86] = {.name = "ESTRPIPE", .desc = ""},
        [ 87] = {.name = "EUSERS", .desc = ""},
        [ 88] = {.name = "ENOTSOCK", .desc = ""},
        [ 89] = {.name = "EDESTADDRREQ", .desc = ""},
        [ 90] = {.name = "EMSGSIZE", .desc = ""},
        [ 91] = {.name = "EPROTOTYPE", .desc = ""},
        [ 92] = {.name = "ENOPROTOOPT", .desc = ""},
        [ 93] = {.name = "EPROTONOSUPPORT", .desc = ""},
        [ 94] = {.name = "ESOCKTNOSUPPORT", .desc = ""},
        [ 95] = {.name = "EOPNOTSUPP", .desc = ""},
        [ 96] = {.name = "EPFNOSUPPORT", .desc = ""},
        [ 97] = {.name = "EAFNOSUPPORT", .desc = ""},
        [ 98] = {.name = "EADDRINUSE", .desc = ""},
        [ 99] = {.name = "EADDRNOTAVAIL", .desc = ""},
        [100] = {.name = "ENETDOWN", .desc = ""},
        [101] = {.name = "ENETUNREACH", .desc = ""},
        [102] = {.name = "ENETRESET", .desc = ""},
        [103] = {.name = "ECONNABORTED", .desc = ""},
        [104] = {.name = "ECONNRESET", .desc = ""},
        [105] = {.name = "ENOBUFS", .desc = ""},
        [106] = {.name = "EISCONN", .desc = ""},
        [107] = {.name = "ENOTCONN", .desc = ""},
        [108] = {.name = "ESHUTDOWN", .desc = ""},
        [109] = {.name = "ETOOMANYREFS", .desc = ""},
        [110] = {.name = "ETIMEDOUT", .desc = ""},
        [111] = {.name = "ECONNREFUSED", .desc = ""},
        [112] = {.name = "EHOSTDOWN", .desc = ""},
        [113] = {.name = "EHOSTUNREACH", .desc = ""},
        [114] = {.name = "EALREADY", .desc = ""},
        [115] = {.name = "EINPROGRESS", .desc = ""},
        [116] = {.name = "ESTALE", .desc = ""},
        [117] = {.name = "EUCLEAN", .desc = ""},
        [118] = {.name = "ENOTNAM", .desc = ""},
        [119] = {.name = "ENAVAIL", .desc = ""},
        [120] = {.name = "EISNAM", .desc = ""},
        [121] = {.name = "EREMOTEIO", .desc = ""},
        [122] = {.name = "EDQUOT", .desc = ""},
        [123] = {.name = "ENOMEDIUM", .desc = ""},
        [124] = {.name = "EMEDIUMTYPE", .desc = ""},
        [125] = {.name = "ECANCELED", .desc = ""},
        [126] = {.name = "ENOKEY", .desc = ""},
        [127] = {.name = "EKEYEXPIRED", .desc = ""},
        [128] = {.name = "EKEYREVOKED", .desc = ""},
        [129] = {.name = "EKEYREJECTED", .desc = ""},
        [130] = {.name = "EOWNERDEAD", .desc = ""},
        [131] = {.name = "ENOTRECOVERABLE", .desc = ""},
        [132] = {.name = "ERFKILL", .desc = ""},
        [133] = {.name = "EHWPOISON", .desc = ""},
        [512] = {.name = "ERESTARTSYS", .desc = "To be restarted if SA_RESTART is set"},
        [513] = {.name = "ERESTARTNOINTR", .desc = "To be restarted"},
        [514] = {.name = "ERESTARTNOHAND", .desc = "To be restarted if no handler"},
        [515] = {.name = "ENOIOCTLCMD", .desc = ""},
        [516] = {.name = "ERESTART_RESTARTBLOCK", .desc = "Interrupted by signal"},
        [517] = {.name = "EPROBE_DEFER", .desc = ""},
        [518] = {.name = "EOPENSTALE", .desc = ""},
        [521] = {.name = "EBADHANDLE", .desc = ""},
        [522] = {.name = "ENOTSYNC", .desc = ""},
        [523] = {.name = "EBADCOOKIE", .desc = ""},
        [524] = {.name = "ENOTSUPP", .desc = ""},
        [525] = {.name = "ETOOSMALL", .desc = ""},
        [526] = {.name = "ESERVERFAULT", .desc = ""},
        [527] = {.name = "EBADTYPE", .desc = ""},
        [528] = {.name = "EJUKEBOX", .desc = ""},
        [529] = {.name = "EIOCBQUEUED", .desc = ""},
        [530] = {.name = "ERECALLCONFLICT", .desc = ""},
};

#endif