#ifndef SIGTAB_H
#define SIGTAB_H

t_sigtab sigtab[32] = {
        [SIGILL]{"SIGILL", {"", "ILL_ILLOPC", "ILL_ILLOPN", "ILL_ILLADR", "ILL_ILLTRP", "ILL_PRVOPC","ILL_PRVREG", "ILL_COPROC"}},
        [SIGTRAP]{"SIGTRAP", {"", "TRAP_BRKPT", "TRAP_TRACE"}},
        [SIGBUS]{"SIGBUS", {"", "BUS_ADRALN", "BUS_ADRERR", "BUS_OBJERR"}},
        [SIGFPE]{"SIGFPE", {"", "FPE_INTDIV", "FPE_INTOVF", "FPE_FLTDIV", "FPE_FLTOVF", "FPE_FLTUND", "FPE_FLTRES", "FPE_FLTINV", "FPE_FLTSUB"}},
        [SIGSEGV]{"SIGSEGV", {"", "SEGV_MAPERR", "SEGV_ACCERR"}},
        [SIGCHLD]{"SIGCHLD", {"", "CLD_EXITED", "CLD_KILLED", "CLD_DUMPED", "CLD_TRAPPED", "CLD_STOPPED", "CLD_CONTINUED"}},
        [SIGPOLL]{"SIGPOLL", {"", "POLL_IN", "POLL_OUT", "POLL_MSG", "POLL_ERR", "POLL_PRI", "POLL_HUP"}},
        [SIGINT]{"SIGINT", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGABRT]{"SIGABRT", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGTERM]{"SIGTERM", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGHUP]{"SIGHUP", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGQUIT]{"SIGQUIT", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGKILL]{"SIGKILL", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGSYS]{"SIGSYS", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGPIPE]{"SIGPIPE", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGALRM]{"SIGALRM", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGURG]{"SIGURG", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGSTOP]{"SIGSTOP", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGTSTP]{"SIGTSTP", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGCONT]{"SIGCONT", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGTTIN]{"SIGTTIN", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGTTOU]{"SIGTTOU", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGXCPU]{"SIGXCPU", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGXFSZ]{"SIGXFSZ", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGVTALRM]{"SIGVTALRM", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGPROF]{"SIGPROF", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGUSR1]{"SIGUSR1", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGUSR2]{"SIGUSR2", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
        [SIGWINCH]{"SIGWINCH", {"SI_USER", "SI_QUEUE", "SI_TIMER", "SI_MESGQ", "SI_ASYNCIO", "SI_SIGIO", "SI_TKILL", [60] = "SI_ASYNCNL"}},
};

#endif